### ISSUE TITLE
Working fine iOS, But unable to slide slider in android

### ISSUE THREAD

**Issue by NirmalsinhRathod** [flyskywhy/react-native-smooth-slider#10]
Hi,

I had implement this library, Now it's working fine in iOS, But in Android the slider is not working

**Comment by flyskywhy** [comment]
more info such as android ver react-native ver? cause it working fine on many android phone

**Comment by Tenpeter** [comment]
@flyskywhy It doesn't work inside a Dialog, I've tried it on https://wix.github.io/react-native-ui-lib/docs/components/overlays/Dialog and https://www.npmjs.com/package/react-native-simple-dialogs

**Comment by flyskywhy** [comment]
@Tenpeter

`@flyskywhy/react-native-modal-animated` perform a workaround for react-native-gesture-handler [Doesn't work in a modal](https://github.com/software-mansion/react-native-gesture-handler/issues/139#issuecomment-857474011) issue
