### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.

### ISSUE THREAD

**Issue by jenschr** [flyskywhy/react-native-smooth-slider#11]
Hi,
I stubled upon your project while looking for a slider that made it simple to adjust the hit-area of the slider. Great job with this!

After adding it, I now get the warning above. It is mentioned in this rather long thread as well and affects lots of code https://github.com/facebook/react-native/issues/33557

Since it's just a warning, I can just ingore it for now but I thought I'd let you know. I'm using react 17.0.2 with react-native 0.68.2.

**Comment by philpettican118** [comment]
Here's a patch to use with https://github.com/ds300/patch-package until there's a new release:

diff --git a/node_modules/react-native-smooth-slider/src/Slider.js b/node_modules/react-native-smooth-slider/src/Slider.js
index fbce285..9d97a47 100644
--- a/node_modules/react-native-smooth-slider/src/Slider.js
+++ b/node_modules/react-native-smooth-slider/src/Slider.js
@@ -10,8 +10,8 @@ import {
     Image,
     StyleSheet,
     View,
-    ViewPropTypes,
 } from 'react-native';
+import { ViewPropTypes } from 'deprecated-react-native-prop-types';
 
 import {
     PanGestureHandler,
