### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.source')

### ISSUE THREAD

**Issue by julste** [flyskywhy/react-native-smooth-slider#13]
I've updated my app to expo SDK 46, which also includes react native version 0.69.3

Only importing the slider:
`import Slider from "react-native-smooth-slider";`

throws the error:
`TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.source')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:46:19 in errorHandler
at node_modules/expo-dev-launcher/build/DevLauncherErrorManager.js:51:24 in <anonymous>
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
`

**Comment by julste** [comment]
Maybe adding and using ImagePropTypes will fix it:

`import { ViewPropTypes, ImagePropTypes } from 'deprecated-react-native-prop-types';` line 14

`trackImage: ImagePropTypes.source,` line 174

`thumbImage: ImagePropTypes.source,` line 184

**Comment by flyskywhy** [comment]
react-native-smooth-slider@1.3.6 fix it :yum:
