### ISSUE TITLE
Disabled prop not working

### ISSUE THREAD

**Issue by anoraxdev** [flyskywhy/react-native-smooth-slider#3]
When setting disabled to true, the value of the slide remains but the thumb can still be moved across the slide. Is there a way to fix this?

**Comment by anoraxdev** [comment]
Thanks! It works great now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by anoraxdev** [comment]
Hi Li,
I'm trying the debugTouchArea prop but it's not showing me anything. I don't know why, but the thumb starts to act funny when close to the left edge of the screen, I try to move it but instead the entire screen moves with my finger and goes to the previous screen.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by flyskywhy** [comment]
debugTouchArea is broken when I forked from jeanregisser/react-native-slider and added react-native-gesture-handler support, I think it's useless of debugTouchArea, so maybe it time to remove debugTouchArea in README.md 😝

**Comment by anoraxdev** [comment]
Oh, ok.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
