### ISSUE TITLE
onValueChange gets called only on drag event, not when a user taps on a slider

### ISSUE THREAD

**Issue by agnieszkabugla** [flyskywhy/react-native-smooth-slider#4]
I've got the following issue with the slider. The value of the slider gets updated only on drag event. When a user taps on a slider, the thumb gets moved, but the value is not updated. Is there anything we can do about this? 

[https://photos.app.goo.gl/Py4ACcyHkSvo7rFH7](video)

``` 
<Slider
  style={{ width: "100%", padding: 10 }}
  minimumValue={this.props.minimumValue}
  maximumValue={this.props.maximumValue}
  step={1}
  minimumTrackTintColor={this.props.minimumTrackTintColor}
  maximumTrackTintColor={this.props.maximumTrackTintColor}
  trackStyle={this.props.trackStyle}
  thumbStyle={this.props.thumbStyle}
  value={this.state.value}
  thumbImage={this.props.thumbImage}
  trackImage={this.props.trackImage}
  onValueChange={(value) => this.setState({value})}
/>
<Text>{this.state.value}</Text>
```

**Comment by jainRashiTFT** [comment]
hey did u find any soln?

**Comment by flyskywhy** [comment]
Only  `onSlidingComplete` is invoked when a user taps on a slider. So you can

    onSlidingComplete={(value) => this.setState({value})}
