### ISSUE TITLE
Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web'.

### ISSUE THREAD

**Issue by karpov-denys** [flyskywhy/react-native-smooth-slider#5]
I have one extra issues with react-native-web. Some interfaces are changed on RN-web and RN.  And now I have this problem with 'ViewPropTypes' is not exported from 'react-native-web'. ->
`/node_modules/react-native-smooth-slider/src/Slider.js
Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web'.`
Could you please provide instruction how to some this?
Here is the problem - https://github.com/necolas/react-native-web/issues/1537#issuecomment-619969653

**Comment by flyskywhy** [comment]
Just see this issue today, don't know why github not notify me that there is a new issue.

You can ref to this https://github.com/reactrondev/react-native-web-swiper/issues/41#issuecomment-685207381
